# Generated by Django 3.2.8 on 2021-10-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=100)),
                ('button_text', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='media/slider_images/%Y/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
