# Generated by Django 3.2.8 on 2021-10-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='youtube_link',
            field=models.URLField(default='#'),
        ),
    ]
