# Generated by Django 3.2.8 on 2021-10-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='video_url',
            field=models.URLField(default='https://www.youtube.com/link'),
        ),
    ]
