# Generated by Django 3.2.8 on 2021-10-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20211022_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('cannon', 'cannon'), ('sony', 'sony'), ('go pro', 'go pro'), ('dslr', 'dslr'), ('other', 'other')], default='cannon', max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('teaching', 'teaching'), ('mobile review', 'mobile review'), ('technology', 'technology'), ('cooking', 'cooking'), ('vlogs', 'vlogs'), ('moto vlogging', 'moto vlogging'), ('comedy', 'comedy'), ('roasting', 'roasting'), ('religious', 'religious'), ('audio story', 'audio story'), ('other', 'other')], default='teaching', max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], default='solo', max_length=255),
        ),
    ]
