# Generated by Django 3.2.8 on 2021-10-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0004_alter_youtuber_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='video_url',
            field=models.CharField(default='https://www.youtube.com/link', max_length=1000),
        ),
    ]
