# Generated by Django 3.2.8 on 2021-10-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0005_alter_youtuber_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('cannon', 'Cannon'), ('sony', 'Sony'), ('go pro', 'Go Pro'), ('dslr', 'DSLR'), ('other', 'Other')], default='cannon', max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('teaching', 'Teaching'), ('mobile review', 'Mobile |Review'), ('technology', '|Technology'), ('cooking', 'Cooking'), ('vlogs', 'Vlogs'), ('moto vlogging', 'Moto Vlogging'), ('comedy', 'Comedy'), ('roasting', 'Roasting'), ('religious', 'Religious'), ('audio story', 'Audio Story'), ('other', 'Other')], default='teaching', max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'Solo'), ('small', 'Small'), ('large', 'Large')], default='solo', max_length=255),
        ),
    ]
