# Generated by Django 3.2.8 on 2021-10-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0006_auto_20211022_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('Cannon', 'Cannon'), ('Sony', 'Sony'), ('Go Pro', 'Go Pro'), ('DSLR', 'DSLR'), ('Other', 'Other')], default='Cannon', max_length=255),
        ),
    ]
