# Generated by Django 3.2.8 on 2021-10-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0007_alter_youtuber_camera_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('teaching', 'Teaching'), ('mobile review', 'Mobile Review'), ('technology', 'Technology'), ('cooking', 'Cooking'), ('vlogs', 'Vlogs'), ('moto vlogging', 'Moto Vlogging'), ('comedy', 'Comedy'), ('roasting', 'Roasting'), ('religious', 'Religious'), ('audio story', 'Audio Story'), ('other', 'Other')], default='teaching', max_length=255),
        ),
    ]
