# Generated by Django 3.2.8 on 2021-10-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacttuber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('fb_link', models.CharField(max_length=2000)),
                ('insta_link', models.CharField(max_length=2000)),
                ('twitter_link', models.CharField(max_length=2000)),
                ('youtube_link', models.CharField(max_length=2000)),
            ],
        ),
    ]
